In [1]:
import pandas as pd
df= pd.read_csv('mock_dataset.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         240 non-null    str
 1   age                 240 non-null    int64
 2   annual_income       228 non-null    float64
 3   tenure_months       240 non-null    int64
 4   monthly_spend       240 non-null    float64
 5   support_tickets_6m  240 non-null    int64
 6   usage_hours_weekly  231 non-null    float64
 7   plan_type           234 non-null    str
 8   region              240 non-null    str
 9   contract_type       240 non-null    str
 10  discount_active     240 non-null    str
 11  churn               240 non-null    int64
dtypes: float64(3), int64(4), str(5)
memory usage: 22.6 KB

In [4]:
df.isnull().sum()

customer_id            0
age                    0
annual_income         12
tenure_months          0
monthly_spend          0
support_tickets_6m     0
usage_hours_weekly     9
plan_type              6
region                 0
contract_type          0
discount_active        0
churn                  0
dtype: int64

In [14]:
df.head(10)

   plan_type
0       True

In [7]:
df.describe()

,age,annual_income,tenure_months,monthly_spend,support_tickets_6m,usage_hours_weekly,churn
count,240.000000,228.000000,240.000000,240.000000,240.000000,231.000000,240.000000
mean,35.570833,62596.614035,32.191667,94.215083,1.795833,17.887446,0.270833
std,9.691647,18487.650953,20.190223,29.736537,1.391841,6.893473,0.445319
min,18.000000,18000.000000,3.000000,15.000000,0.000000,1.000000,0.000000
25%,29.000000,50147.000000,17.000000,75.045000,1.000000,13.250000,0.000000
50%,35.000000,63088.000000,28.500000,94.180000,2.000000,18.200000,0.000000
75%,41.250000,75238.000000,42.000000,112.107500,3.000000,22.800000,1.000000
max,68.000000,114291.000000,84.000000,174.740000,6.000000,37.200000,1.000000

In [8]:
df['annual_income'] = df['annual_income'].fillna(df['annual_income'].median())

In [10]:
df.duplicated().sum()

np.int64(0)

In [22]:
df= pd.get_dummies(df, columns=['plan_type'])

KeyError: "None of [Index(['plan_type'], dtype='str')] are in the [columns]"

In [19]:
df.head(10)

   True
0  True